#include "netcfgn.idl"

[
    uuid(38135d11-e93b-11d1-bb14-0000f8779051),
    version(1.0),
    helpstring("Sample Filter 1.0 Type Library")
]
library SampleFilterLib
{
    [
        uuid(df2e4f67-e93a-11d1-bb14-0000f8779051),
        helpstring("Sample Filter Class")
    ]
    coclass CSampleFilter
    {
        [restricted] interface INetCfgComponentControl;
        [restricted] interface INetCfgComponentSetup;
        [restricted] interface INetCfgComponentPropertyUi;
        [restricted] interface INetCfgComponentNotifyBinding;
        [restricted] interface INetCfgComponentNotifyGlobal;
    };
};

